# Config file for automatic testing at travis-ci.org

language: python

env:
  global:
    - PYTHONPATH=$TRAVIS_BUILD_DIR
  matrix:
    - DJANGO_VERSION="Django>=1.5,<1.6"
    - DJANGO_VERSION="Django>=1.6,<1.7"

python:
  - "3.4"
  - "2.7"
  - "2.6"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install $DJANGO_VERSION
  - pip install -r requirements-test.txt

# command to run tests using coverage, e.g. python setup.py test
script:
  - coverage run --source custom_user `which django-admin.py` test custom_user --settings=test_settings.settings
  - coverage run --append --source custom_user `which django-admin.py` test custom_user --settings=test_settings.settings_subclass

# report coverage to coveralls.io
after_success: coveralls